
#pragma once

enum GameplayMode { GAMEPLAY_MODE_NORMAL, GAMEPLAY_MODE_IRRIGATION };

// Move to somewhere else?
enum GardeningTool {
    GARDENING_TOOL_NONE,
    GARDENING_TOOL_IRRIGATOR,
    GARDENING_TOOL_NUTRIENTS,
    GARDENING_TOOL_PLANTER,
    GARDENING_TOOL_PLANT_CUTTING,
    GARDENING_TOOL_TRASH_BIN,
};
