
#include "../../utils/utils.h"

#define SCENE_SCALE_INITIAL (1.0f * WORLD_SCALE)
#define SCENE_SCALE_STEP 0.4f
#define SCENE_SCALE_MIN SCENE_SCALE_INITIAL - (2 * SCENE_SCALE_STEP)
#define SCENE_SCALE_MAX SCENE_SCALE_INITIAL + (5 * SCENE_SCALE_STEP)

// Garden dimensions
#define GARDEN_COLS 14
#define GARDEN_ROWS 12
#define GARDEN_TILE_COUNT (GARDEN_COLS * GARDEN_ROWS)

// Legacy constants for backward compatibility
#define GARDEN_SCALE_INITIAL SCENE_SCALE_INITIAL
#define GARDEN_SCALE_STEP SCENE_SCALE_STEP
#define GARDEN_SCALE_MIN SCENE_SCALE_MIN
#define GARDEN_SCALE_MAX SCENE_SCALE_MAX

extern IsoTransform SCENE_TRANSFORM;
